name: PrCheck

on:
  pull_request:
    branches:
      - '*'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: psf/black@stable
        with:
          black_args: ". --check"