name: Upload Python Package

on:
  push:
    branches:
      - feature/pip

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set Setup version
      shell: pwsh
      run: |
        (Get-Content -path ./setup.py -Raw) -replace 'version=.*','version=${{github.ref_name}},' | Set-Content -Path ./setup.py
      if: startsWith(github.ref, 'refs/tags/v')

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
      # if: startsWith(github.ref, 'refs/tags/v')

    - name: Build package
      run: python -m build
      # if: startsWith(github.ref, 'refs/tags/v')

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/v')
